use_frameworks!

platform :ios, '8.0'

target 'ZJScrollPageView_Example' do
  pod 'ZJScrollPageView_Private', :path => '../'

  target 'ZJScrollPageView_Tests' do
    inherit! :search_paths

    
  end
end
